(function() {var implementors = {};
implementors["libc"] = [];implementors["glib"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glib/struct.Bytes.html' title='glib::Bytes'>Bytes</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glib/variant/struct.Variant.html' title='glib::variant::Variant'>Variant</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glib/struct.VariantType.html' title='glib::VariantType'>VariantType</a>",];implementors["gio"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glib/bytes/struct.Bytes.html' title='glib::bytes::Bytes'>Bytes</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glib/variant/struct.Variant.html' title='glib::variant::Variant'>Variant</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glib/variant_type/struct.VariantType.html' title='glib::variant_type::VariantType'>VariantType</a>",];implementors["gtk"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glib/bytes/struct.Bytes.html' title='glib::bytes::Bytes'>Bytes</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glib/variant/struct.Variant.html' title='glib::variant::Variant'>Variant</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glib/variant_type/struct.VariantType.html' title='glib::variant_type::VariantType'>VariantType</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
