(function() {var implementors = {};
implementors["cairo"] = ["impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="glib/variant_type/struct.VariantTy.html" title="struct glib::variant_type::VariantTy">VariantTy</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html" title="struct std::ffi::c_str::CStr">CStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html" title="struct std::ffi::os_str::OsStr">OsStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/path/struct.Path.html" title="struct std::path::Path">Path</a>",];
implementors["gdk"] = ["impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="glib/variant_type/struct.VariantTy.html" title="struct glib::variant_type::VariantTy">VariantTy</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html" title="struct std::ffi::c_str::CStr">CStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html" title="struct std::ffi::os_str::OsStr">OsStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/path/struct.Path.html" title="struct std::path::Path">Path</a>",];
implementors["gdk_pixbuf"] = ["impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html" title="struct std::ffi::c_str::CStr">CStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html" title="struct std::ffi::os_str::OsStr">OsStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/path/struct.Path.html" title="struct std::path::Path">Path</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="glib/variant_type/struct.VariantTy.html" title="struct glib::variant_type::VariantTy">VariantTy</a>",];
implementors["gio"] = ["impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="glib/variant_type/struct.VariantTy.html" title="struct glib::variant_type::VariantTy">VariantTy</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html" title="struct std::ffi::c_str::CStr">CStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html" title="struct std::ffi::os_str::OsStr">OsStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/path/struct.Path.html" title="struct std::path::Path">Path</a>",];
implementors["glib"] = ["impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html" title="struct std::ffi::c_str::CStr">CStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html" title="struct std::ffi::os_str::OsStr">OsStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/path/struct.Path.html" title="struct std::path::Path">Path</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="glib/struct.VariantTy.html" title="struct glib::VariantTy">VariantTy</a>",];
implementors["gtk"] = ["impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html" title="struct std::ffi::c_str::CStr">CStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html" title="struct std::ffi::os_str::OsStr">OsStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/path/struct.Path.html" title="struct std::path::Path">Path</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="glib/variant_type/struct.VariantTy.html" title="struct glib::variant_type::VariantTy">VariantTy</a>",];
implementors["libc"] = ["impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html" title="struct std::ffi::c_str::CStr">CStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html" title="struct std::ffi::os_str::OsStr">OsStr</a>","impl <a class="trait" href="https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html" title="trait collections::borrow::ToOwned">ToOwned</a> for <a class="struct" href="https://doc.rust-lang.org/nightly/std/path/struct.Path.html" title="struct std::path::Path">Path</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
